# This is a basic workflow to help you get started with Actions

name: 自动部署文档

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: 安装pnpm
              run: npm i -g pnpm

            - name: 安装依赖
              run: pnpm i

            - name: 配置git
              run: git config --global user.email "guojikun486546@163.com" && git config --global user.name "GuoJikun"

            - name: build and deploy
              env:
                  ACCESS_TOKEN: ${{ secrets.git_token }}
                  BRANCH: gh-pages
              run: npm run build

            - name: 部署文档到gh-pages
              env:
                  ACCESS_TOKEN: ${{ secrets.git_token }}
              run: cd dist && git config --global init.defaultBranch main && git init && git add -A && git commit -m "deploy" && git push -f https://$ACCESS_TOKEN@github.com/GuoJikun/fox-captcha.git main:gh-pages
